version: '3.8'

services:
  # Build a Pokemon Server Service
  server:
    container_name: pokemon-server
    build: 
      context: ./pokemon-server/
      dockerfile: dockerfile
    working_dir: /server
    volumes:
      - .:/server
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - pokemon-net

# Remeber to execute: docker network create pokemon-net
networks:
  pokemon-net:
    external: true