version: '3.8'

services:
  # Build a Postgresql DB Service
  database:
    image: postgres:latest
    container_name: pokemon-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: pokemon
    networks:
      - pokemon-net

# Remeber to execute: docker network create pokemon-net
networks:
  pokemon-net:
    external: true